import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/util/Providers";
import { Toaster } from "sonner";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { ClientSessionProvider } from "@/util/ClientSessionProvider";
import SnippetsProvider from "@/context/snippetsContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientSessionProvider>
      <html lang="en">
        <body className={GeistSans.className}>
          <Provider>
            <SnippetsProvider>{children}</SnippetsProvider>
            <Toaster />
          </Provider>
        </body>
      </html>
    </ClientSessionProvider>
  );
}
